/*
 * This Groovy source file was generated by the Gradle 'init' task.
 */
package kafka
import kafka.service.ProcessadorVaga
import kafka.controller.EmailFactory
import kafka.controller.GetEmails
class App {
    static void main(String[] args) {
        ProcessadorVaga processadorVaga = new ProcessadorVaga()
        processadorVaga.processaVaga()
    }
}
